# --- !Ups

create table "USER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    "first_name" VARCHAR NOT NULL, "last_name" VARCHAR NOT NULL,
    "email_address" VARCHAR NOT NULL, "password" VARCHAR NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL);

# --- !Downs

drop table "users";